language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
before_install:
- sudo apt-get install python3-pip
install:
- virtualenv -p python3 venv
- source venv/bin/activate
- pip3 install -r requirements.txt
- pip3 install -r requirements_dev.txt
- pip3 install -e .
script:
- python3 -m pytest -v -x automated_test.py
 
